all:
	@echo "make check  -- to run all examples"

check: run_python_examples

run_python_examples:
	R -s --no-restore --file=pcats_api_example_manuscript_1.R
	R -s --no-restore --file=pcats_api_example_manuscript_1B.R
	R -s --no-restore --file=pcats_api_example_manuscript_2.R
	R -s --no-restore --file=pcats_api_example_manuscript_3.R
	R -s --no-restore --file=pcats_api_example_manuscript_3G.R
	R -s --no-restore --file=pcats_api_example_manuscript_4.R
	R -s --no-restore --file=pcats_api_example_manuscript_5.R
	R -s --no-restore --file=pcats_api_example_manuscript_6.R
	R -s --no-restore --file=pcats_api_example_manuscript_6B.R
	R -s --no-restore --file=pcats_api_example_manuscript_7.R
	R -s --no-restore --file=pcats_api_example_manuscript_8.R
