all:
	@echo "make check  -- to run all examples"

check: run_python_examples

run_python_examples:
	python3 pcats_api_example_manuscript_1.py
	python3 pcats_api_example_manuscript_1B.py
	python3 pcats_api_example_manuscript_2.py
	python3 pcats_api_example_manuscript_3.py
	python3 pcats_api_example_manuscript_3G.py
	python3 pcats_api_example_manuscript_4.py
	python3 pcats_api_example_manuscript_5.py
	python3 pcats_api_example_manuscript_6.py
	python3 pcats_api_example_manuscript_6B.py
	python3 pcats_api_example_manuscript_7.py
	python3 pcats_api_example_manuscript_8.py
