all:
	@echo "make check  -- to run all examples"

check: run_curl_examples

run_curl_examples:
	./pcats_api_example_manuscript_1.sh
	./pcats_api_example_manuscript_1B.sh
	./pcats_api_example_manuscript_2.sh
	./pcats_api_example_manuscript_3.sh
	./pcats_api_example_manuscript_3G.sh
	./pcats_api_example_manuscript_4.sh
	./pcats_api_example_manuscript_5.sh
	./pcats_api_example_manuscript_6.sh
	./pcats_api_example_manuscript_6B.sh
	./pcats_api_example_manuscript_7.sh
	./pcats_api_example_manuscript_8.sh
